#
# Prevents creeper explosions from breaking blocks. 
# Default: true
disableGriefing = false
#
# Multiplier for extra knockback caused by the explosion.
# Set to 0.0 for vanilla behavior.
# Default: 4.0
knockbackMult = 2.5
#
# Multiplier for extra knockback caused by the explosion to players.
# Set to -1.0 to default to the value of knockbackMult.
# Default: 3.5
playerKnockbackMult = -1.0
#
# Adjusts the upward velocity added by the explosion as part of its knockback.
# Default: 0.1
knockbackUp = 0.2
#
# Exponent used for calculating the falloff.
# Default: 2.5
falloffExponent = 2.5

